version: "3"

services:
  app:
    container_name: project-resizer
    image: ghcr.io/yoganovvaindra/resizer:latest
    networks:
      - Tunnel
    ports:
      - 5001:5000
    restart: unless-stopped

networks:
  tunnel:
    external: true